require("dotenv").config();
const express = require("express");
const axios = require("axios");
const router = express.Router();

const SPOTIFY_BASE = "https://api.spotify.com/v1/";

const createPlaylist = (access_token, name, user_id) => {
  return axios.post(
    `${SPOTIFY_BASE}users/${user_id}/playlists`,
    {
      name: name + " Playlist",
      description: "Playlist generated by Rythmonica",
    },
    {
      headers: {
        Authorization: `Bearer ${access_token}`,
        "Content-Type": "application/json",
      },
    }
  );
};

const addSongsToPlaylist = (access_token, trackUris, playlist_id) => {
  return axios.post(
    `${SPOTIFY_BASE}playlists/${playlist_id}/tracks?uris=${trackUris}`,
    {},
    {
      headers: {
        Authorization: `Bearer ${access_token}`,
        "Content-Type": "application/json",
      },
    }
  );
};

router.post("/create", (req, res) => {
  const { trackUris, relatedToName, user_id } = req.query;
  const access_token = req.cookies.access_token;

  createPlaylist(access_token, relatedToName, user_id).then((response) => {
    // console.log(response.data);
    addSongsToPlaylist(access_token, trackUris, response.data.id).then(
      (response) => {
        // console.log(response.data);
        res.status(201).send();
      }
    );
  });
});

module.exports = router;
